import type { Element } from "./types";

/** All 118 elements with layout positions for the standard periodic table */
export const ELEMENTS: Element[] = [
  { atomicNumber: 1, symbol: "H", name: "Hydrogen", category: "non_metal", period: 1, group: 1, uses: ["fuel", "water"], funFact: "Hydrogen is the lightest element and makes up about 75% of the universe!" },
  { atomicNumber: 2, symbol: "He", name: "Helium", category: "noble_gas", period: 1, group: 18, uses: ["balloons", "coolant"], funFact: "Helium makes your voice sound squeaky because sound travels faster through it!" },
  { atomicNumber: 3, symbol: "Li", name: "Lithium", category: "metal", period: 2, group: 1, uses: ["batteries", "medicine"], funFact: "Lithium batteries power most smartphones and electric vehicles." },
  { atomicNumber: 4, symbol: "Be", name: "Beryllium", category: "metal", period: 2, group: 2, uses: ["aerospace", "xray_windows"], funFact: "Beryllium is used in spacecraft because it is both light and strong." },
  { atomicNumber: 5, symbol: "B", name: "Boron", category: "metalloid", period: 2, group: 13, uses: ["glass", "detergents"], funFact: "Boron compounds help make heat-resistant glass for kitchenware." },
  { atomicNumber: 6, symbol: "C", name: "Carbon", category: "non_metal", period: 2, group: 14, uses: ["diamond", "graphite", "life"], funFact: "Carbon is the basis of all known life — you are mostly made of carbon!" },
  { atomicNumber: 7, symbol: "N", name: "Nitrogen", category: "non_metal", period: 2, group: 15, uses: ["fertilizers", "atmosphere"], funFact: "About 78% of the air you breathe is nitrogen." },
  { atomicNumber: 8, symbol: "O", name: "Oxygen", category: "non_metal", period: 2, group: 16, uses: ["breathing", "medicine"], funFact: "Oxygen makes up about 21% of Earth's atmosphere and is essential for life." },
  { atomicNumber: 9, symbol: "F", name: "Fluorine", category: "halogen", period: 2, group: 17, uses: ["toothpaste", "nonstick"], funFact: "Fluorine is the most reactive element — it reacts with almost everything!" },
  { atomicNumber: 10, symbol: "Ne", name: "Neon", category: "noble_gas", period: 2, group: 18, uses: ["signs", "lasers"], funFact: "Neon gas glows bright red-orange in advertising signs." },
  { atomicNumber: 11, symbol: "Na", name: "Sodium", category: "metal", period: 3, group: 1, uses: ["salt", "street_lights"], funFact: "Sodium street lights glow yellow-orange and are very energy efficient." },
  { atomicNumber: 12, symbol: "Mg", name: "Magnesium", category: "metal", period: 3, group: 2, uses: ["alloys", "fireworks"], funFact: "Magnesium burns with a brilliant white flame — that's why it's used in fireworks!" },
  { atomicNumber: 13, symbol: "Al", name: "Aluminium", category: "metal", period: 3, group: 13, uses: ["cans", "aircraft", "foil"], funFact: "Aluminium is lightweight yet strong — perfect for soda cans and airplanes." },
  { atomicNumber: 14, symbol: "Si", name: "Silicon", category: "metalloid", period: 3, group: 14, uses: ["chips", "glass", "solar"], funFact: "Silicon chips power every computer and smartphone on Earth." },
  { atomicNumber: 15, symbol: "P", name: "Phosphorus", category: "non_metal", period: 3, group: 15, uses: ["fertilizers", "matches"], funFact: "White phosphorus glows in the dark — the word 'phosphorus' means 'light bearer'." },
  { atomicNumber: 16, symbol: "S", name: "Sulfur", category: "non_metal", period: 3, group: 16, uses: ["fertilizers", "rubber"], funFact: "Sulfur smells like rotten eggs and is found near volcanoes." },
  { atomicNumber: 17, symbol: "Cl", name: "Chlorine", category: "halogen", period: 3, group: 17, uses: ["water_purification", "pools"], funFact: "Chlorine keeps swimming pools clean by killing harmful bacteria." },
  { atomicNumber: 18, symbol: "Ar", name: "Argon", category: "noble_gas", period: 3, group: 18, uses: ["light_bulbs", "welding"], funFact: "Argon fills incandescent light bulbs to prevent the filament from burning out." },
  { atomicNumber: 19, symbol: "K", name: "Potassium", category: "metal", period: 4, group: 1, uses: ["fertilizers", "bananas"], funFact: "Bananas are rich in potassium, which helps your muscles work properly." },
  { atomicNumber: 20, symbol: "Ca", name: "Calcium", category: "metal", period: 4, group: 2, uses: ["bones", "cement", "milk"], funFact: "Calcium builds strong bones and teeth — dairy products are great sources!" },
  { atomicNumber: 21, symbol: "Sc", name: "Scandium", category: "metal", period: 4, group: 3, uses: ["alloys", "sports"], funFact: "Scandium-aluminium alloys are used in high-end bicycle frames." },
  { atomicNumber: 22, symbol: "Ti", name: "Titanium", category: "metal", period: 4, group: 4, uses: ["aircraft", "implants"], funFact: "Titanium is as strong as steel but about 45% lighter!" },
  { atomicNumber: 23, symbol: "V", name: "Vanadium", category: "metal", period: 4, group: 5, uses: ["steel", "batteries"], funFact: "Vanadium strengthens steel used in tools and car parts." },
  { atomicNumber: 24, symbol: "Cr", name: "Chromium", category: "metal", period: 4, group: 6, uses: ["stainless_steel", "chrome"], funFact: "Chromium gives stainless steel its shiny, rust-resistant surface." },
  { atomicNumber: 25, symbol: "Mn", name: "Manganese", category: "metal", period: 4, group: 7, uses: ["steel", "batteries"], funFact: "Manganese is essential for making strong steel and healthy bones." },
  { atomicNumber: 26, symbol: "Fe", name: "Iron", category: "metal", period: 4, group: 8, uses: ["steel", "blood", "construction"], funFact: "Iron in your blood carries oxygen — that's why it's called hemoglobin!" },
  { atomicNumber: 27, symbol: "Co", name: "Cobalt", category: "metal", period: 4, group: 9, uses: ["batteries", "magnets", "paint"], funFact: "Cobalt gives blue glass and ceramics their beautiful color." },
  { atomicNumber: 28, symbol: "Ni", name: "Nickel", category: "metal", period: 4, group: 10, uses: ["coins", "batteries", "alloys"], funFact: "Nickel is used in many coins and rechargeable batteries." },
  { atomicNumber: 29, symbol: "Cu", name: "Copper", category: "metal", period: 4, group: 11, uses: ["electrical_wiring", "coins", "plumbing"], funFact: "Copper is one of the best conductors of electricity and is widely used in electrical wiring." },
  { atomicNumber: 30, symbol: "Zn", name: "Zinc", category: "metal", period: 4, group: 12, uses: ["galvanizing", "batteries", "sunscreen"], funFact: "Zinc coating on steel prevents rust — that's called galvanization." },
  { atomicNumber: 31, symbol: "Ga", name: "Gallium", category: "metal", period: 4, group: 13, uses: ["semiconductors", "thermometers"], funFact: "Gallium melts in your hand at about 30°C — just above room temperature!" },
  { atomicNumber: 32, symbol: "Ge", name: "Germanium", category: "metalloid", period: 4, group: 14, uses: ["fiber_optics", "semiconductors"], funFact: "Germanium was used in early transistor radios before silicon took over." },
  { atomicNumber: 33, symbol: "As", name: "Arsenic", category: "metalloid", period: 4, group: 15, uses: ["semiconductors", "wood_preservative"], funFact: "Arsenic compounds were once used in medicines — in tiny, controlled doses!" },
  { atomicNumber: 34, symbol: "Se", name: "Selenium", category: "non_metal", period: 4, group: 16, uses: ["glass", "photocopiers"], funFact: "Selenium makes glass red and helps photocopiers work." },
  { atomicNumber: 35, symbol: "Br", name: "Bromine", category: "halogen", period: 4, group: 17, uses: ["photography", "flame_retardants"], funFact: "Bromine is one of only two elements that are liquid at room temperature!" },
  { atomicNumber: 36, symbol: "Kr", name: "Krypton", category: "noble_gas", period: 4, group: 18, uses: ["lighting", "lasers"], funFact: "Krypton is used in high-speed photography flash lamps." },
  { atomicNumber: 37, symbol: "Rb", name: "Rubidium", category: "metal", period: 5, group: 1, uses: ["atomic_clocks", "research"], funFact: "Rubidium atoms tick incredibly precisely in atomic clocks." },
  { atomicNumber: 38, symbol: "Sr", name: "Strontium", category: "metal", period: 5, group: 2, uses: ["fireworks", "bone_health"], funFact: "Strontium compounds create brilliant red colors in fireworks." },
  { atomicNumber: 39, symbol: "Y", name: "Yttrium", category: "metal", period: 5, group: 3, uses: ["leds", "superconductors"], funFact: "Yttrium helps make the red color in LED screens." },
  { atomicNumber: 40, symbol: "Zr", name: "Zirconium", category: "metal", period: 5, group: 4, uses: ["nuclear", "jewelry"], funFact: "Zirconium is used in nuclear reactors because it doesn't absorb neutrons easily." },
  { atomicNumber: 41, symbol: "Nb", name: "Niobium", category: "metal", period: 5, group: 5, uses: ["steel", "superconductors"], funFact: "Niobium makes steel stronger for pipelines and jet engines." },
  { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", category: "metal", period: 5, group: 6, uses: ["steel", "lubricants"], funFact: "Molybdenum helps plants fix nitrogen from the air." },
  { atomicNumber: 43, symbol: "Tc", name: "Technetium", category: "metal", period: 5, group: 7, uses: ["medical_imaging"], funFact: "Technetium was the first artificially produced element." },
  { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", category: "metal", period: 5, group: 8, uses: ["electronics", "catalysts"], funFact: "Ruthenium hardens platinum and palladium alloys." },
  { atomicNumber: 45, symbol: "Rh", name: "Rhodium", category: "metal", period: 5, group: 9, uses: ["catalytic_converters", "jewelry"], funFact: "Rhodium is one of the most expensive metals — used in catalytic converters." },
  { atomicNumber: 46, symbol: "Pd", name: "Palladium", category: "metal", period: 5, group: 10, uses: ["catalytic_converters", "electronics"], funFact: "Palladium can absorb 900 times its volume in hydrogen gas!" },
  { atomicNumber: 47, symbol: "Ag", name: "Silver", category: "metal", period: 5, group: 11, uses: ["jewelry", "electronics", "photography"], funFact: "Silver is the best conductor of electricity of all elements." },
  { atomicNumber: 48, symbol: "Cd", name: "Cadmium", category: "metal", period: 5, group: 12, uses: ["batteries", "pigments"], funFact: "Cadmium gives yellow and red pigments their vivid colors." },
  { atomicNumber: 49, symbol: "In", name: "Indium", category: "metal", period: 5, group: 13, uses: ["touchscreens", "solders"], funFact: "Indium tin oxide makes touchscreens work when you tap them." },
  { atomicNumber: 50, symbol: "Sn", name: "Tin", category: "metal", period: 5, group: 14, uses: ["solder", "cans", "alloys"], funFact: "Tin has been used for thousands of years — bronze is copper plus tin!" },
  { atomicNumber: 51, symbol: "Sb", name: "Antimony", category: "metalloid", period: 5, group: 15, uses: ["flame_retardants", "alloys"], funFact: "Ancient Egyptians used antimony compounds as eye makeup." },
  { atomicNumber: 52, symbol: "Te", name: "Tellurium", category: "metalloid", period: 5, group: 16, uses: ["solar", "alloys"], funFact: "Tellurium helps solar panels convert sunlight into electricity." },
  { atomicNumber: 53, symbol: "I", name: "Iodine", category: "halogen", period: 5, group: 17, uses: ["medicine", "salt"], funFact: "Iodized salt prevents goiter — a swelling of the thyroid gland." },
  { atomicNumber: 54, symbol: "Xe", name: "Xenon", category: "noble_gas", period: 5, group: 18, uses: ["headlights", "anesthesia"], funFact: "Xenon headlights produce a bright, white light for better night driving." },
  { atomicNumber: 55, symbol: "Cs", name: "Caesium", category: "metal", period: 6, group: 1, uses: ["atomic_clocks", "drilling"], funFact: "Caesium defines the length of one second in atomic clocks worldwide." },
  { atomicNumber: 56, symbol: "Ba", name: "Barium", category: "metal", period: 6, group: 2, uses: ["medical_imaging", "fireworks"], funFact: "Barium meals help doctors see your digestive system on X-rays." },
  { atomicNumber: 57, symbol: "La", name: "Lanthanum", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["camera_lenses", "batteries"], funFact: "Lanthanum glass makes high-quality camera lenses." },
  { atomicNumber: 58, symbol: "Ce", name: "Cerium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["catalytic_converters", "polishing"], funFact: "Cerium is the most abundant rare earth element." },
  { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["magnets", "lasers"], funFact: "Praseodymium creates the green color in glass and ceramics." },
  { atomicNumber: 60, symbol: "Nd", name: "Neodymium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["magnets", "headphones"], funFact: "Neodymium magnets are the strongest permanent magnets known!" },
  { atomicNumber: 61, symbol: "Pm", name: "Promethium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["nuclear_batteries"], funFact: "Promethium glows in the dark and is named after Prometheus." },
  { atomicNumber: 62, symbol: "Sm", name: "Samarium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["magnets", "cancer_treatment"], funFact: "Samarium-cobalt magnets work at very high temperatures." },
  { atomicNumber: 63, symbol: "Eu", name: "Europium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["euro_banknotes", "phosphors"], funFact: "Euro banknotes use europium to prevent counterfeiting under UV light!" },
  { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["mri", "nuclear"], funFact: "Gadolinium helps doctors see clearer MRI scans." },
  { atomicNumber: 65, symbol: "Tb", name: "Terbium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["green_phosphors", "sonar"], funFact: "Terbium creates the green glow in fluorescent lamps." },
  { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["magnets", "lasers"], funFact: "Dysprosium makes magnets work at high temperatures in electric cars." },
  { atomicNumber: 67, symbol: "Ho", name: "Holmium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["magnets", "lasers"], funFact: "Holmium has the highest magnetic strength of any element." },
  { atomicNumber: 68, symbol: "Er", name: "Erbium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["fiber_optics", "lasers"], funFact: "Erbium amplifies signals in fiber optic internet cables." },
  { atomicNumber: 69, symbol: "Tm", name: "Thulium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["portable_xray", "lasers"], funFact: "Thulium is used in portable X-ray machines." },
  { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["atomic_clocks", "steel"], funFact: "Ytterbium atomic clocks could be even more precise than caesium ones." },
  { atomicNumber: 71, symbol: "Lu", name: "Lutetium", category: "metal", period: 6, group: 3, series: "lanthanide", uses: ["pet_scans", "catalysts"], funFact: "Lutetium is the heaviest and hardest of the lanthanide elements." },
  { atomicNumber: 72, symbol: "Hf", name: "Hafnium", category: "metal", period: 6, group: 4, uses: ["nuclear", "microchips"], funFact: "Hafnium controls nuclear reactions in power plants." },
  { atomicNumber: 73, symbol: "Ta", name: "Tantalum", category: "metal", period: 6, group: 5, uses: ["capacitors", "surgery"], funFact: "Tantalum capacitors are tiny but store a lot of charge in phones." },
  { atomicNumber: 74, symbol: "W", name: "Tungsten", category: "metal", period: 6, group: 6, uses: ["light_bulbs", "tools"], funFact: "Tungsten has the highest melting point of all elements — 3,422°C!" },
  { atomicNumber: 75, symbol: "Re", name: "Rhenium", category: "metal", period: 6, group: 7, uses: ["jet_engines", "catalysts"], funFact: "Rhenium lets jet engine parts survive extreme heat." },
  { atomicNumber: 76, symbol: "Os", name: "Osmium", category: "metal", period: 6, group: 8, uses: ["pen_tips", "fountain_pens"], funFact: "Osmium is the densest naturally occurring element." },
  { atomicNumber: 77, symbol: "Ir", name: "Iridium", category: "metal", period: 6, group: 9, uses: ["spark_plugs", "crucibles"], funFact: "An iridium layer marks the asteroid impact that wiped out the dinosaurs." },
  { atomicNumber: 78, symbol: "Pt", name: "Platinum", category: "metal", period: 6, group: 10, uses: ["jewelry", "catalytic_converters"], funFact: "Platinum is rarer than gold and resists corrosion beautifully." },
  { atomicNumber: 79, symbol: "Au", name: "Gold", category: "metal", period: 6, group: 11, uses: ["jewelry", "electronics", "coins"], funFact: "All the gold ever mined would fit in about three Olympic swimming pools." },
  { atomicNumber: 80, symbol: "Hg", name: "Mercury", category: "metal", period: 6, group: 12, uses: ["thermometers", "barometers"], funFact: "Mercury is the only metal that is liquid at room temperature!" },
  { atomicNumber: 81, symbol: "Tl", name: "Thallium", category: "metal", period: 6, group: 13, uses: ["electronics", "glass"], funFact: "Thallium compounds were once used as rat poison — handle with care!" },
  { atomicNumber: 82, symbol: "Pb", name: "Lead", category: "metal", period: 6, group: 14, uses: ["batteries", "shielding"], funFact: "Lead blocks radiation — that's why it's used in X-ray aprons." },
  { atomicNumber: 83, symbol: "Bi", name: "Bismuth", category: "metal", period: 6, group: 15, uses: ["medicine", "cosmetics"], funFact: "Bismuth creates rainbow-colored crystals that are popular in chemistry demos." },
  { atomicNumber: 84, symbol: "Po", name: "Polonium", category: "metal", period: 6, group: 16, uses: ["nuclear", "research"], funFact: "Polonium was discovered by Marie Curie and named after her homeland, Poland." },
  { atomicNumber: 85, symbol: "At", name: "Astatine", category: "halogen", period: 6, group: 17, uses: ["cancer_treatment"], funFact: "Astatine is so rare that less than 30 grams exist on Earth at any time." },
  { atomicNumber: 86, symbol: "Rn", name: "Radon", category: "noble_gas", period: 6, group: 18, uses: ["cancer_treatment"], funFact: "Radon can seep into homes from the ground — test your basement!" },
  { atomicNumber: 87, symbol: "Fr", name: "Francium", category: "metal", period: 7, group: 1, uses: ["research"], funFact: "Francium is extremely radioactive and incredibly rare." },
  { atomicNumber: 88, symbol: "Ra", name: "Radium", category: "metal", period: 7, group: 2, uses: ["glow_in_dark", "medicine"], funFact: "Marie Curie discovered radium — it once made watch dials glow in the dark." },
  { atomicNumber: 89, symbol: "Ac", name: "Actinium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["cancer_treatment"], funFact: "Actinium glows blue in the dark due to its radioactivity." },
  { atomicNumber: 90, symbol: "Th", name: "Thorium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["nuclear", "lanterns"], funFact: "Thorium could power next-generation nuclear reactors safely." },
  { atomicNumber: 91, symbol: "Pa", name: "Protactinium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Protactinium is one of the rarest naturally occurring elements." },
  { atomicNumber: 92, symbol: "U", name: "Uranium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["nuclear_power", "research"], funFact: "Uranium fuels nuclear power plants that generate about 10% of world electricity." },
  { atomicNumber: 93, symbol: "Np", name: "Neptunium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Neptunium was the first transuranium element ever made in a lab." },
  { atomicNumber: 94, symbol: "Pu", name: "Plutonium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["nuclear", "space"], funFact: "Plutonium powers NASA's deep space probes like Voyager." },
  { atomicNumber: 95, symbol: "Am", name: "Americium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["smoke_detectors"], funFact: "There's a tiny bit of americium in most home smoke detectors!" },
  { atomicNumber: 96, symbol: "Cm", name: "Curium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["space", "research"], funFact: "Curium is named after Marie and Pierre Curie, pioneers of radioactivity." },
  { atomicNumber: 97, symbol: "Bk", name: "Berkelium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Berkelium was first made at the University of California, Berkeley." },
  { atomicNumber: 98, symbol: "Cf", name: "Californium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["neutron_source", "research"], funFact: "Californium helps detect gold and silver in mining operations." },
  { atomicNumber: 99, symbol: "Es", name: "Einsteinium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Einsteinium was discovered in the fallout of the first hydrogen bomb test." },
  { atomicNumber: 100, symbol: "Fm", name: "Fermium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Fermium is named after physicist Enrico Fermi." },
  { atomicNumber: 101, symbol: "Md", name: "Mendelevium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Mendelevium honors Dmitri Mendeleev, creator of the periodic table!" },
  { atomicNumber: 102, symbol: "No", name: "Nobelium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Nobelium is named after Alfred Nobel, who invented dynamite." },
  { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", category: "metal", period: 7, group: 3, series: "actinide", uses: ["research"], funFact: "Lawrencium is named after Ernest Lawrence, inventor of the cyclotron." },
  { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", category: "metal", period: 7, group: 4, uses: ["research"], funFact: "Rutherfordium is named after Ernest Rutherford, who discovered the nucleus." },
  { atomicNumber: 105, symbol: "Db", name: "Dubnium", category: "metal", period: 7, group: 5, uses: ["research"], funFact: "Dubnium is named after Dubna, Russia, where it was first made." },
  { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", category: "metal", period: 7, group: 6, uses: ["research"], funFact: "Seaborgium is the only element named after a living person — Glenn Seaborg." },
  { atomicNumber: 107, symbol: "Bh", name: "Bohrium", category: "metal", period: 7, group: 7, uses: ["research"], funFact: "Bohrium honors Niels Bohr, who explained how atoms are structured." },
  { atomicNumber: 108, symbol: "Hs", name: "Hassium", category: "metal", period: 7, group: 8, uses: ["research"], funFact: "Hassium is named after Hesse, the German state where it was discovered." },
  { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", category: "metal", period: 7, group: 9, uses: ["research"], funFact: "Meitnerium honors Lise Meitner, who helped discover nuclear fission." },
  { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", category: "metal", period: 7, group: 10, uses: ["research"], funFact: "Darmstadtium was first created in Darmstadt, Germany." },
  { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", category: "metal", period: 7, group: 11, uses: ["research"], funFact: "Roentgenium is named after Wilhelm Röntgen, discoverer of X-rays." },
  { atomicNumber: 112, symbol: "Cn", name: "Copernicium", category: "metal", period: 7, group: 12, uses: ["research"], funFact: "Copernicium honors Nicolaus Copernicus, who said Earth orbits the Sun." },
  { atomicNumber: 113, symbol: "Nh", name: "Nihonium", category: "metal", period: 7, group: 13, uses: ["research"], funFact: "Nihonium is the first element discovered in Asia — 'Nihon' means Japan." },
  { atomicNumber: 114, symbol: "Fl", name: "Flerovium", category: "metal", period: 7, group: 14, uses: ["research"], funFact: "Flerovium is named after the Flerov Laboratory in Russia." },
  { atomicNumber: 115, symbol: "Mc", name: "Moscovium", category: "metal", period: 7, group: 15, uses: ["research"], funFact: "Moscovium honors the Moscow region where it was discovered." },
  { atomicNumber: 116, symbol: "Lv", name: "Livermorium", category: "metal", period: 7, group: 16, uses: ["research"], funFact: "Livermorium is named after Livermore, California, home of its discovery lab." },
  { atomicNumber: 117, symbol: "Ts", name: "Tennessine", category: "halogen", period: 7, group: 17, uses: ["research"], funFact: "Tennessine is named after Tennessee, where it was first made." },
  { atomicNumber: 118, symbol: "Og", name: "Oganesson", category: "noble_gas", period: 7, group: 18, uses: ["research"], funFact: "Oganesson is the heaviest element ever made — only a few atoms at a time!" },
];

export const ELEMENT_MAP = new Map(
  ELEMENTS.map((element) => [element.atomicNumber, element])
);

export function getElementByNumber(n: number): Element | undefined {
  return ELEMENT_MAP.get(n);
}
